### ISSUE TITLE
Gitart Scroll Carousel  + Nuxt 3

### ISSUE THREAD

**Issue by thefubon** [gitart-group/scroll-carousel#1]
Please tell me how to install a slider in Nuxt 3

**Comment by MichaelGitArt** [comment]
Hello, @thefubon. There is a problem with code splitting with Vite build. Probably it will be fixed in further versions.

For now, I suggest using not bundled components from the package:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/34610289/199802253-f0ff9a38-e49d-4f93-9c6f-3b2864112674.png">

**Comment by thefubon** [comment]
Thanks
